[_]
schema-version = "0.2"

[project]
id = "simple-express-app"
name = "Simple Express App"
version = "1.0.0"

[[build.env]]
name = "NODE_ENV"
value = "production"

[[build.env]]
name = "PORT"
value = "8001"

[[build.buildpacks]]
uri = "heroku/nodejs"

[metadata]
description = "Simple Express.js application"

[metadata.dokku]
port = 8001

[metadata.deploy]
port = 8001
