[_]
schema-version = "0.2"

[project]
id = "simple-flask-app"
name = "Simple Flask App"
version = "1.0.0"

[[build.env]]
name = "FLASK_ENV"
value = "production"

[[build.env]]
name = "PORT"
value = "8001"

[[build.env]]
name = "PYTHONPATH"
value = "."

[[build.buildpacks]]
uri = "heroku/python"

[metadata]
description = "Simple Flask Python application"

[metadata.dokku]
port = 8001

[metadata.deploy]
port = 8001
