[[build.env]]
name = "PORT"
value = "5000"

[[build.env]]
name = "PYTHONPATH"
value = "."

# Cloud Native Buildpack port configuration
[[build.buildpacks]]
uri = "heroku/python"

->

[[build.env]]
name = "PORT"
value = "8001"

[[build.env]]
name = "PYTHONPATH"
value = "."

[[build.env]]
name = "FLASK_APP"
value = "/opt/app.py"

# Cloud Native Buildpack port configuration
[[build.buildpacks]]
uri = "heroku/python"

# Define processes
[build.processes]
web = "FLASK_APP=/opt/app.py flask run --host=0.0.0.0 --port=8001"
